#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

#genera los 10 espacios de trabajo
bspc monitor -d 一 二 三 四 五 六 七 八 九 十

#1 2 3 4 5 6 7 8 9 10

#一 二 三 四 五 六 七 八 九 十

#I II III IV V VI VII VIII IX X

#inicio de polybar con 1 segundo de espera
sleep 1
$HOME/.config/polybar/launch.sh $

#fondo de pantalla
nitrogen --restore &

#polkit app que requieren sudo
lxqt-policykit-agent &

#picom
picom &

bspc config border_width         2
bspc config window_gap          12

# Configurar los bordes de las ventanas activas y no activas
bspc config border_width 4
bspc config border_radius 10
bspc config focused_border_color "#f0c674"
bspc config normal_border_color "#282828"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

#tema
lxappearance $
